version: '3.8'

services:
  api:
    image: qhaofdev/rest-api:1.0.0
    container_name: rest_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: